---
# packages.yml

- name: Install system packages
  ansible.builtin.apt:
    name: "{{ ubuntu_packages }}"

- name: Install extra packages
  ansible.builtin.apt:
    name: "{{ ubuntu_packages_extra }}"
  when: ansible_distribution_version >= '18.04'

- name: Python packages for monitoring
  ansible.builtin.command: pip3 install --break-system-packages {{
    pip_packages|join(' ') }}
  args:
    creates: /usr/local/lib/python{{
      ansible_python.version.major }}.{{ ansible_python.version.minor
      }}/dist-packages/mdstat
