apiVersion: v2
name: immich
description: Immich media server
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/immich-app/immich
- https://github.com/instantlinux/docker-tools
type: application
version: 0.1.0
# Reminder, update tag for ml instance in values.yaml
appVersion: v2.7.5
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
- name: ml
  version: 0.1.0
  repository: file://subcharts/ml
- name: postgres
  version: 0.1.0
  repository: file://subcharts/postgres
- name: valkey
  version: 0.1.0
  repository: file://subcharts/valkey
