apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
        host: 0.0.0.0
        port: 3000
        base_url: http://localhost:3000
        cookie_secret_path: /etc/headplane/cookie_secret
        cookie_secure: true
      headscale:
        url: {{ .Values.headscale_url }}
        config_path: /etc/headscale/config.yaml
      kubernetes:
        enabled: true
