---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "local.fullname" . }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "local.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "local.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "local.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
          - { name: API_TOKEN_SECRET, value: git.{{ .Values.mydomain }}-api-token }
          - { name: REPO_PREFIX, value: {{ .Values.repoPrefix }} }
          - { name: SSH_PORT, value: "{{ .Values.sshPort }}" }
          - { name: TZ, value: {{ .Values.tz }} }
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /var/backup
            name: backup
            subPath: {{ .Chart.Name }}
          - mountPath: /var/log
            name: logs
          - name: secret-sshkey
            mountPath: /run/secrets/git-dump_sshkey
            subPath: git-dump-sshkey
          - name: secret-token
            mountPath: /run/secrets/git.{{ .Values.mydomain }}-api-token
            subPath: git.{{ .Values.mydomain }}-api-token
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      - name: backup
        hostPath: { path: {{ .Values.k8s.backupPath }} }
      - name: logs
        hostPath: { path: {{ .Values.k8s.volumesPath }}/sync-logs/{{ .Chart.Name }} }
      - name: secret-sshkey
        secret:
          secretName: git-dump-sshkey
      - name: secret-token
        secret:
          secretName: git.{{ .Values.mydomain }}-api-token
