apiVersion: v2
name: headplane
description: UI for headscale
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/tale/headplane
type: application
version: 0.1.0
# specify version tag from ghcr.io in top-level values.yaml
appVersion: "0.0.1"
dependencies:
- name: chartlib
  version: 0.1.8
  repository: https://instantlinux.github.io/docker-tools
