#!/bin/sh
# $Id: check_disk_status,v 1.6 2010/12/06 04:04:39 richb Exp $

WARN=90
CRIT=95
SKIP_DISKS="loop|docker/containers|docker/device|kubelet/pods|/dev/mapper/data01-volmyth|/dev/mapper/data04-pvr01mythdata|/dev/mapper/luks-vol2014|luks-vol2015|luks-vol2016"
MAX_USE=0

# Note:  the programs 'cut' and 'awk' are in:
#  /usr/bin on OpenSUSE
#  /bin on RHEL
# hence we do not specify the full path for those

for disk in `/bin/egrep ":|^/dev" /etc/mtab | grep -v " ro 0 " |grep -v " ro,relatime"| egrep -v "$SKIP_DISKS" | cut -f2 -d\  `
do
  output=`/bin/df -PH $disk | /bin/egrep -v "^Filesystem|tmpfs|cdrom"`
  partition=$(/bin/echo $output | awk '{ print $1}' )
  usep=$(/bin/echo $output | awk '{ print $5}' | cut -d'%' -f1  )
  if [ $usep -gt $MAX_USE ]
  then
    MAX_USE=$usep
    BIGGEST_PART=$partition
  fi
  if [ \! $usep ]; then
    # probably stale file handle
    exit 1;
  fi
done
echo $BIGGEST_PART at $MAX_USE%
if [ $MAX_USE -ge $CRIT ]; then
  exit 2;
elif [ $MAX_USE -ge $WARN ]; then
  exit 1;
fi
exit 0;
