#!/bin/bash

set -e -u -o pipefail

readonly state_ok=0
readonly state_critical=2

usage() {
  echo "Usage: $0 [-h] -- [etcdctl-args...]"
  echo
  echo 'Options:'
  echo '  -h  Display usage and exit'
  echo
  echo 'Global options for etcdctl can be passed after a double dash (--).'
  echo
  echo 'Example:'
  echo "  $0 -- --endpoints https://server1:2379,https://server2:2379"
}

while getopts 'h' opt; do
  case "$opt" in
    h)
      usage
      exit 0
      ;;
    *)
      usage >&2
      exit 1
      ;;
  esac
done

shift $((OPTIND - 1))

tmpfile=$(mktemp)
trap 'rm -f "$tmpfile"' EXIT

if etcdctl "$@" cluster-health > "$tmpfile" 2>&1; then
  ret=0
else
  ret="$?"
fi

if [[ "$ret" -eq 0 ]]; then
  echo 'Cluster is healthy'
  exit "$state_ok"
fi

# Multi-line output
# http://docs.icinga.org/latest/en/pluginapi.html#outputspec
echo 'Cluster is unhealthy |'
cat "$tmpfile"
exit "$state_critical"

# vim: set sw=2 sts=2 et :
