# Variables for Kubernetes resources
#   These are referred to from within ./install/*.yaml files and
#   docker-compose files under ../services. Customize values as needed
# NOTE: for helm, for each chart instance provide a yaml file as
#   ~/docker/admin/services/values/<chart>.yaml to override values;
#   global overrides can be placed in ~/docker/admin/services/values.yaml.

export DOMAIN               ?= domain.com

export CLUSTER_NETWORK      ?= flannel
export DB_HOST              ?= db00.$(DOMAIN)
export EDITOR               ?= vi
export K8S_NAMESPACE        ?= worker
export K8S_NODES            ?= kube1.$(DOMAIN) kube2.$(DOMAIN) kube3.$(DOMAIN)
export K8S_WORKER_COUNT     ?= 3
export K8S_VOLUMES_PATH     ?= /var/lib/docker/k8s-volumes
export LOG_NAMESPACE        ?= logging
export LOG_TO_SPLUNK        ?=
export MYTHTV_VOL_SIZE      ?= 400Gi
export NAMED_VOLUMES        ?= share $(LOCAL_VOLUMES)
export NFS_HOST             ?= nfs.$(DOMAIN)
export POOL_NUM_MEDIUM      ?= 0010
export POOL_NUM_SMALL       ?= 0030
export POOL_SIZE_LARGE       = 20Gi
export POOL_SIZE_MEDIUM      = 8Gi
export POOL_SIZE_SMALL       = 500Mi
export TZ                   ?= UTC

# IP addresses - TODO replace static IPs with names, if practical
export COREDNS_IP           ?= 10.96.0.10
export MONITOR_EXT_IP       ?= 192.168.1.20
export NODE_LOCAL_DNS_IP    ?= 169.254.0.10
export RSYSLOGD_IP          ?= 10.101.1.40

# Ports configured in ingress-nginx.yaml
# export PORT_DOVECOT_IMAPD    ?= 843
# export PORT_DOVECOT_IMAPS    ?= 993
# export PORT_DOVECOT_SMTP     ?= 825
# export PORT_GIT_SSH          ?= 8999
# # export PORT_POSTFIX_INTERNAL ?= 3425
# export PORT_POSTFIX_EXTERNAL ?= 3525
