# Default values for git-dump.
replicaCount: 1
k8s: {}
mydomain: example.com
repoPrefix: git@git.example.com
sshPort: 22

image:
  repository: instantlinux/git-dump
  pullPolicy: IfNotPresent
  tag: "2.30.2-r0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}

podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  enabled: false

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector: {}
tolerations: []
affinity: {}
