# Default values for mt-daapd.
replicaCount: 2

env:
  server_banner: "%h Firefly MP3 via Docker"
hostNetwork: true
volumeMounts:
- name: cache
  mountPath: /var/cache/forked-daapd
- name: music
  mountPath: /srv/music
  readOnly: true
volumes:
- name: cache
  emptyDir: {}
- name: music
  persistentVolumeClaim:
    claimName: mp3

image:
  repository: instantlinux/mt-daapd
  pullPolicy: IfNotPresent
  tag: "26.4-dfsg1-1"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount: {}
deployment: {}
podAnnotations: {}
podSecurityContext: {}
securityContext: {}

service:
  enabled: false

ingress:
  enabled: false

resources: {}

autoscaling:
  enabled: false

nodeSelector:
  service.mt-daapd: allow

tolerations: []
affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
    - labelSelector:
        matchExpressions:
        - key: app.kubernetes.io/name
          operator: In
          values:
          - mt-daapd
      topologyKey: "kubernetes.io/hostname"
