apiVersion: v2
name: gitea
description: Gitea source code management
home: https://github.com/instantlinux/docker-tools
sources:
- https://github.com/instantlinux/docker-tools
- https://github.com/go-gitea/gitea
type: application
version: 28.0.0
appVersion: 28.0.0-rootless
dependencies:
- name: chartlib
  version: 0.1.11
  repository: oci://ghcr.io/instantlinux/charts
  # also available at oci://registry-1.docker.io/instantlinux
