{{- if hasKey .Values.gateway "listeners" }}
{{- range .Values.gateway.listeners }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: TCPRoute
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.namespace }}
spec:
  parentRefs:
  - name: {{ $.Values.gateway.name }}
    sectionName: {{ .name }}
  rules:
  - backendRefs:
    - name: {{ .service }}
      port: {{ .port }}
{{- end }}
{{- end }}
