{{- if or .Values.rsyslogExt.enabled (not (hasKey .Values "rsyslogExt.enabled")) }}
---
# for remote VPN-connected systems
apiVersion: v1
kind: Service
metadata:
  name: rsyslogd-external
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "local.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
  - { port: 514, nodePort: {{ .Values.rsyslogExt.nodePort }}, targetPort: 514, name: rsyslogd }
  selector:
    app.kubernetes.io/name: rsyslogd
  sessionAffinity: ClientIP
{{- end }}
