---
- name: Ensure ubuntu repos available
  ansible.builtin.deb822_repository:
    name: ubuntu
    types: [ deb, deb-src ]
    uris: "{{ ubuntu_repo_uri }}"
    suites:
    - "{{ ansible_facts['distribution_release'] }}"
    - "{{ ansible_facts['distribution_release'] }}-updates"
    - "{{ ansible_facts['distribution_release'] }}-security"
    - "{{ ansible_facts['distribution_release'] }}-backports"
    components: [ main, restricted, universe, multiverse ]
    signed_by: /usr/share/keyrings/ubuntu-archive-keyring.gpg

- name: Docker repo
  ansible.builtin.deb822_repository:
    name: docker
    types: [ deb ]
    uris: "{{ docker.apt_repo.url }}"
    suites: [ "{{ ansible_facts['distribution_release'] }}" ]
    components: [ stable ]
    signed_by: "{{ docker.apt_repo.url }}/gpg"
