#!/bin/bash
VER1=$(grep "ARG DHCP_VERSION" Dockerfile | cut -d= -f 2)
VER2=$(grep "ARG DNSMASQ_VERSION" Dockerfile | cut -d= -f 2)
docker tag $IMAGE_NAME $DOCKER_REPO:$VER1-$VER2
docker push $DOCKER_REPO:$VER1-$VER2
