# Default values for machine-learning
statefulset:
  containerPorts: [ containerPort: 3003 ]
  env:
    hf_xet_cache: /cache/huggingface-xet
    immich_log_level: info
    mplconfigdir: /cache/matplotlib-config
    transformers_cache: /cache
  podSecurityContext:
    runAsUser: 1000
    runAsGroup: 1000
    # gids: video, render
    supplementalGroups: [ 44, 891 ]
  replicas: 1
  resources:
    limits:
      cpu: 4000m
      memory: 4096Mi
    requests:
      cpu: 1100m
      memory: 768Mi
livenessProbe:
  httpGet:
    path: /ping
    port: 3003
readinessProbe:
  httpGet:
    path: /ping
    port: 3003
volumeMounts:
- mountPath: /cache
  name: cache
- mountPath: /dev/dri
  name: dri
volumes:
- name: dri
  hostPath:
    path: /dev/dri
volumeClaimTemplates:
- metadata:
    name: cache
  spec:
    accessModes: [ ReadWriteOnce ]
    resources:
      requests:
        storage: 8Gi

image:
  repository: ghcr.io/immich-app/immich-machine-learning
  pullPolicy: IfNotPresent
  # tag: default

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  enabled: false
service:
  ports: [ port: 3003 ]
  type: LoadBalancer
autoscaling:
  enabled: false
