name: Publish Helm Charts

env:
  REGISTRY: ghcr.io
  CHART_DIR: k8s/helm

on:
  push:
    branches: [main, SYS-673_envoy_gateway]
    paths:
    - k8s/helm/**/Chart.yaml
    - images/**/helm/Chart.yaml

jobs:
  find-charts:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: List Chart.yaml Updates
        id: set-matrix
        run: |
          CHANGED=$(git diff --name-only HEAD^ HEAD | \
            grep -E "^(${CHART_DIR}/.*|images/.*/helm)/Chart.yaml" | \
            awk '{sub(/\/[^/]+$/, ""); print}' | \
            jq -R . | jq -s -c .)
          echo "matrix={\"chart\":$CHANGED}" >> $GITHUB_OUTPUT

  publish:
    needs: find-charts
    if: ${{ needs.find-charts.outputs.matrix != '{"chart":[]}' &&
            needs.find-charts.outputs.matrix != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix: ${{ fromJson(needs.find-charts.outputs.matrix) }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # - name: Configure Git
    #   run: |
    #     git config user.name "$GITHUB_ACTOR"
    #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v4

    - name: Log in to OCI Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Package and Push
      run: |
        helm dependency update "${{ matrix.chart }}"
        helm package "${{ matrix.chart }}"
        helm push "$(echo *.tgz)" oci://ghcr.io/${{ github.repository_owner }}/helm-charts
