#!/bin/bash
curl -X post https://hooks.microbadger.com/images/instantlinux/samba/AbUeiFAJXC_w4QrQxRCVIw-N7Lk=
curl -X post https://hooks.microbadger.com/images/instantlinux/samba-arm64/z5rP54xFs1uRxNQy9YfntUHRQeE=
curl -X post https://hooks.microbadger.com/images/instantlinux/samba-arm32/cxM0u3FypTWJYcYQIMFc5K-e-Qc=
